### PR TITLE
fix slider padding

### PR DESCRIPTION
**Pull request by cyan-2048**
on KaiOS, input[type="range"] has padding...

### CODE REVIEW

**Comment by cyan-2048** [comment]
`git commit -m "hotfix #2"`

lmao didn't know it mentions a pull request when doing `#`

**Comment by canicjusz** [comment]
yea it does xD

**Comment by LolloDev5123** [comment]
!

**Comment by cyan-2048** [comment]
since i got notified, i realized the pull request i made is useless, just use `all:unset` on all the elements that have browser default styling (inputs, buttons), the `all` property works in KaiOS

**Pull request closed without merging**
